### ISSUE TITLE
async_forward_entry_setup warning in home assistant

### ISSUE THREAD

**Issue by BottlecapDave** [GeorgeSG/ha-slack-user#12]
Thanks for providing a great integration. I use it all the time to update my slack status' automatically based on my WFH state.

In HA, there is currently the following warning being raised
```
Detected code that calls async_forward_entry_setup for integration slack_user, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue
```

It looks like you have some time to fix it, but wanted to let you know in case you hadn't seen it.

**Comment by MrFinchMkV** [comment]
I created a PR regarding this issue: https://github.com/GeorgeSG/ha-slack-user/pull/13

**Comment by override80** [comment]
Hi @GeorgeSG ,

on 2024.11 I'm having this issue after bumping to 0.6:

```
2024-11-07 01:15:11.550 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry slack_jobtome for slack_user
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/slack_user/init.py", line 15, in async_setup_entry
    hass.async_create_task(
  File "/usr/src/homeassistant/homeassistant/core.py", line 819, in async_create_task
    return self.async_create_task_internal(target, name, eager_start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 841, in async_create_task_internal
    task = create_eager_task(target, name=name, loop=self.loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got True

```

I tried a different way, since there are deprecation warnings for async_forward_entry_setup in favour of async_forward_entry_setups (note the 's'). More here: https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

I'll submit a PR with my proposal.
